### ISSUE TITLE
Build Failure: libaddrxlat.so.0 - DSO missing

### ISSUE THREAD

**Issue by sdimitro** [ptesarik/libkdumpfile#20]
That may be just a problem with my setup but better to be safe than sorry.

After running `configure`, I get the following error when running `make`:
```
make[2]: Entering directory '/export/home/delphix/libkdumpfile/examples'
/bin/bash ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o showxlat showxlat.o  ../src/kdumpfile/libkdumpfile.la
libtool: link: gcc -g -O2 -o .libs/showxlat showxlat.o  ../src/kdumpfile/.libs/libkdumpfile.so
/usr/bin/ld: showxlat.o: undefined reference to symbol 'addrxlat_sys_decref@@LIBADDRXLAT_0'
//export/home/delphix/libkdumpfile/src/addrxlat/.libs/libaddrxlat.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:448: recipe for target 'showxlat' failed
make[2]: *** [showxlat] Error 1
```

I believe the issue is that do not include `libaddrxlat` for the example so it misses references to it. I tried to verify this by doing the following after the error:
```
$ cd examples
$ /bin/bash ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o showxlat showxlat.o  ../src/kdumpfile/libkdumpfile.la ../src/addrxlat/libaddrxlat.la
libtool: link: gcc -g -O2 -o .libs/showxlat showxlat.o  ../src/kdumpfile/.libs/libkdumpfile.so ../src/addrxlat/.libs/libaddrxlat.so
$ echo $?
0
```
[I basically added `../src/addrxlat/.libs/libaddrxlat.so` at the end]

Rerunning `make` after that, the compilation continues until the end.

**Comment by ptesarik** [comment]
It's interesting that the error did not happen in my environment, but since showxlat calls a libaddrxlat function explicitly, the libtool library should indeed be added.

**Comment by sdimitro** [comment]
Closing since #21 has been merged.
