### ISSUE TITLE
please use pkg-config to look up zlib requirements

### ISSUE THREAD

**Issue by vapier** [ptesarik/libkdumpfile#3]
rather than probe zlib via AC_SEARCH_LIBS, please use PKG_CHECK_MODULES.  this handles transitive deps (not that zlib really has any), as well as esoteric include/library paths.

call `PKG_PROG_PKG_CONFIG` at the top, and then do something like:
```
  PKG_CHECK_MODULES([ZLIB], [zlib])
  AS_VAR_APPEND([CFLAGS], " $ZLIB_CFLAGS")
  AS_VAR_APPEND([LIBS], " $ZLIB_LIBS")
```

**Comment by ptesarik** [comment]
Fixed with commit e1506d4a9b118723a762fd55f2c483bd93ee5e0e.

Thanks for helping improve libkdumpfile!
