### ISSUE TITLE
test failures when running `make checks`

### ISSUE THREAD

**Issue by sdimitro** [ptesarik/libkdumpfile#31]
With the patch used in the other issue that I opened (https://github.com/ptesarik/libkdumpfile/issues/30), I was able to run the tests but hit the following two failures:
```
$ cat tests/test-suite.log
==============================================
   libkdumpfile 0.3.0: tests/test-suite.log
==============================================

# TOTAL: 153
# PASS:  151
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 1

.. contents:: :depth: 2

ERROR: diskdump-basic-snappy
============================

Unsupported compression flags: 4
Creating page bitmap
Creating page data
Cannot create DISKDUMP file
ERROR diskdump-basic-snappy (exit status: 99)

FAIL: lkcd-unordered-faroff
===========================

Creating page data
Created LKCD dump: out/lkcd-unordered-faroff.dump
Data: 00
4E 6F 4D 61 67 69 63 21
Wrong data found
FAIL lkcd-unordered-faroff (exit status: 1)
```

**Comment by sdimitro** [comment]
ok scratch the `snappy` part that problem was on my side as `libsnappy-dev` was not installed correctly.

As for `lkcd-unordered-faroff.dump` it seems like `dumpdata` returns some zeros in the front with a newline and that triggers the failure. Here is what `dumpdata` returns:
```
$ ./dumpdata out/lkcd-unordered-faroff.dump 0x2fff 9
00
4E 6F 4D 61 67 69 63 21
```
and here is what we expect:
```
magic="4E 6F 4D 61 67 69 63 21"
```

**Comment by ptesarik** [comment]
The output of `dumpdata` is in fact correct, but the check fails. I think that's a shell incompatibility.

@sdimitro: What shell are you using (what is your `/bin/sh` linked to)?

**Comment by ptesarik** [comment]
Never mind, it's probably `dash`. I have found its built-in `echo` command is … well, incompatible.
