### ISSUE TITLE
Regression introduced with the latest vmcoreinfo conversion change

### ISSUE THREAD

**Issue by sdimitro** [ptesarik/libkdumpfile#32]
= Description

Seems like the regression was introduced with this change: https://github.com/ptesarik/libkdumpfile/commit/b4b3c94cc24dc88d08701ebe35f72a1f1785046a

= Reproducer

Download reference crash dump from S3 and unarchive it:
```
$ aws s3 cp --no-sign-request s3://sdb-regression-dumps/dump-201912060006.tar.lzma .
$ tar -x --lzma -f dump-201912060006.tar.lzma
```

Run `dumpattr` to it and ask for the raw vmcoreinfo:
```
$ dumpattr  dump-data/dump.201912060006 linux.vmcoreinfo.raw
```

Output before:
```
linux.vmcoreinfo.raw: OSRELEASE=5.0.0-36-generic
PAGESIZE=4096
SYMBOL(init_uts_ns)=ffffffff8c817540
SYMBOL(node_online_map)=ffffffff8ca3dbc0
SYMBOL(swapper_pg_dir)=ffffffff8c80e000
SYMBOL(_stext)=ffffffff8b200000
SYMBOL(vmap_area_list)=ffffffff8c8e85d0
SYMBOL(mem_section)=ffffa0897ffcd000
LENGTH(mem_section)=2048
SIZE(mem_section)=16
...<cropped output ; keeps going >...
```

Output now:
```
linux.vmcoreinfo.raw: [ 4F5352454C454153453D352E302E302D33362D67656E657269630A5041474553495A453D343039360A53594D424F4C28696E69745F7574735F6E73293D666666666666666638633831373534300A53594D424F4C286E6F64655F6F6E6C696E655F6D6170293D666666666666666638636133646263300A53594D424F4C28737761707065725F70675F646972293D666666666666666638633830653030300A53594D424F4C285F7374657874293D666666666666666638623230303030300A53594D424F4C28766D61705F617265615F6C697374293D666666666666666638633865383564300A53594D424F4C286D656D5F73656374696F6E293D666666666130383937666663643030300A4C454E475448286D656D5F73656374696F6E293D323034380A53495A45286D656D5F73656374696F6E293D31360A4F4646534554286D656D5F73656374696F6E2E73656374696F6E5F6D656D5F6D6170293D300A53495A452870616765293D36340A53495A452870676C6973745F64617461293D3137323836340A53495A45287A6F6E65293D313636340A53495A4528667265655F61726561293D3130340A53495A45286C6973745F68656164293D31360A53495A45286E6F64656D61736B5F74293D3132380A4F464653455428706167652E666C616773293D300A4F464653455428706167652E5F726566636F756E74293D35320A4F464653455428706167652E6D617070696E67293D32340A4F464653455428706167652E6C7275293D380A4F464653455428706167652E5F6D6170636F756E74293D34380A4F464653455428706167652E70726976617465293D34300A4F464653455428706167652E636F6D706F756E645F64746F72293D31360A4F464653455428706167652E636F6D706F756E645F6F72646572293D31370A4F464653455428706167652E636F6D706F756E645F68656164293D380A4F46465345542870676C6973745F646174612E6E6F64655F7A6F6E6573293D300A4F46465345542870676C6973745F646174612E6E725F7A6F6E6573293D3137323139320A4F46465345542870676C6973745F646174612E6E6F64655F73746172745F70666E293D3137323230300A4F46465345542870676C6973745F646174612E6E6F64655F7370616E6E65645F7061676573293D3137323231360A4F46465345542870676C6973745F646174612E6E6F64655F6964293D3137323232340A4F4646534554287A6F6E652E667265655F61726561293D3139320A4F4646534554287A6F6E652E766D5F73746174293D313437320A4F4646534554287A6F6E652E7370616E6E65645F7061676573293D3132300A4F464653455428667265655F617265612E667265655F6C697374293D300A4F4646534554286C6973745F686561642E6E657874293D300A4F4646534554286C6973745F686561642E70726576293D380A4F464653455428766D61705F617265612E76615F7374617274293D300A4F464653455428766D61705F617265612E6C697374293D34380A4C454E475448287A6F6E652E667265655F61726561293D31310A53594D424F4C286C6F675F627566293D666666666666666638633836383061300A53594D424F4C286C6F675F6275665F6C656E293D666666666666666638633836383039630A53594D424F4C286C6F675F66697273745F696478293D666666666666666638636461313131380A53594D424F4C28636C6561725F696478293D666666666666666638636461313065340A53594D424F4C286C6F675F6E6578745F696478293D666666666666666638636461313130380A53495A45287072696E746B5F6C6F67293D31360A4F4646534554287072696E746B5F6C6F672E74735F6E736563293D300A4F4646534554287072696E746B5F6C6F672E6C656E293D380A4F4646534554287072696E746B5F6C6F672E746578745F6C656E293D31300A4F4646534554287072696E746B5F6C6F672E646963745F6C656E293D31320A4C454E47544828667265655F617265612E667265655F6C697374293D360A4E554D424552284E525F465245455F5041474553293D300A4E554D4245522850475F6C7275293D340A4E554D4245522850475F70726976617465293D31330A4E554D4245522850475F737761706361636865293D31300A4E554D4245522850475F737761706261636B6564293D31390A4E554D4245522850475F736C6162293D390A4E554D4245522850475F6877706F69736F6E293D32330A4E554D4245522850475F686561645F6D61736B293D36353533360A4E554D42455228504147455F42554444595F4D4150434F554E545F56414C5545293D2D3132390A4E554D4245522848554745544C425F504147455F44544F52293D320A4E554D42455228706879735F62617365293D343630333234383634300A53594D424F4C28696E69745F746F705F706774293D666666666666666638633830653030300A4E554D4245522870677461626C655F6C355F656E61626C6564293D300A53594D424F4C286E6F64655F64617461293D666666666666666638636133393334300A4C454E475448286E6F64655F64617461293D313032340A4B45524E454C4F46465345543D613230303030300A4E554D424552284B45524E454C5F494D4147455F53495A45293D313037333734313832340A435241534854494D453D313537353539303735330A ]
```
---

I understand that the above output is not necessarily wrong but the original issue I hit was actually from using the C API directly like this:
```
        const char *vmcoreinfo;
        ks = kdump_vmcoreinfo_raw(ctx, &vmcoreinfo);
        if (ks != KDUMP_OK) {
                printf( "kdump_vmcoreinfo_raw: %s\n", kdump_get_err(ctx));
                ret = -1;
                goto out;
        }
        printf("length: %ld\n", strlen(vmcoreinfo) + 1);
        printf("contents:\n%s\n", vmcoreinfo);
```

Apologies if I'm somehow mis-using the API - if this is not a bug please specify what would the correct way of usign `kdump_vmcoreinfo_raw()` be. Looking at the commit it just seems to me that even though we did the conversation to use a binary blob instead of raw string in the underlying implementation, we broke `kdump_vmcoreinfo_raw()` which works with raw strings (meaning `char *`).

**Comment by ptesarik** [comment]
Hi @sdimitro, nice to see someone actually follows the bleeding edge development!

The type change itself is indeed an intentional backwards-incompatible API change that should eventually let `makedumpfile` use this library. If the old behaviour must be retained, I would have to invent another name for the blob attribute and initialize a string attribute from it lazily to maintain API compatibility. I didn't consider the old API stable enough to bother, but I'm open to change my mind if you can elaborate on why `linux.vmcoreinfo.raw` should be retained as a string attribute.

Now, regarding `kdump_vmcoreinfo_raw`, that's a genuine bug (and evidence that this part of the API is not tested). This function has been always bad, because the lifetime of the return value is underspecified. For example, the pointer is invalidated by any change to the vmcoreinfo attributes. In a multi-threaded program, the call is inherently racy. In an extreme case, the pointer may become invalid before it is even returned to the caller. At one point in time, I even considered removing this function from the API.

It can be fixed if the return value is dynamically allocated, and then it can be fixed even after changing the type of the `*.vmcore.raw` attributes. Let me know if that would work for you. It seems that you're currently the only user of this function, so I'll gladly modify it to fit your needs.

**Comment by ptesarik** [comment]
I have implemented my proposal now, but I'm keeping this issue open for a while, awaiting feedback.

The test suite has also been extended with a basic check of kdump_vmcoreinfo_raw() and kdump_vmcoreinfo_line().

**Comment by sdimitro** [comment]
Hi @ptesarik !

Thanks for looking into this so quickly! Yes we have a couple of Github Actions that test the functionality provided to our projects by bleeding-edge libkdumpfile nightly and on every push - this is how this was caught actually.

Skimming through your change, I think your patch should work pretty well with our usage of `kdump_vmcoreinfo_raw`. I'll give it a try soon and report back. If all is well, I'll make sure to close the issue too.

Glad to see by the way that there's going to be a single implementation now for kdump files given that the goal is to have `makedumpfile` use this library too. Your work is very much appreciated by my colleagues and me.

**Comment by sdimitro** [comment]
Forgot to get back to this. New interface LGTM. Closing the issue.
