### ISSUE TITLE
libkdumpfile 0.4.1: multiple test failures on non-x86_64 architectures

### ISSUE THREAD

**Issue by michel-slm** [ptesarik/libkdumpfile#40]
We just enabled libkdumpfile's test suite in Fedora, and multiple tests are failing on non-x86_64 architectures:

https://koji.fedoraproject.org/koji/taskinfo?taskID=86922546

Uploaded the build logs so they are available here and don't get garbage collected; here's a quick listing:

## i686

FAIL: elf-vmcoreinfo
FAIL: elf-dom0-no-phys_base
FAIL: elf-xen_prstatus
FAIL: lkcd-multiread
FAIL: lkcd-duplicate
FAIL: lkcd-duplicate-middle
FAIL: xlat-linux-aarch64-5.8-va39
FAIL: xlat-linux-aarch64-5.8-va48
FAIL: xlat-linux-x86_64-4.12-sme

## aarch64

FAIL: early-version-code
FAIL: elf-prstatus-ppc64
FAIL: elf-vmcoreinfo
FAIL: elf-dom0-no-phys_base
FAIL: multixlat-elf
FAIL: multixlat-same
FAIL: vmci-cleanup

## ppc64le

FAIL: early-version-code
FAIL: elf-prstatus-ppc64
FAIL: elf-vmcoreinfo
FAIL: elf-dom0-no-phys_base
FAIL: multixlat-elf
FAIL: multixlat-same
FAIL: vmci-cleanup

## s390x
FAIL: addrxlat-table
FAIL: early-version-code
FAIL: elf-prstatus-ppc64
FAIL: elf-vmcoreinfo
FAIL: elf-dom0-no-phys_base
FAIL: elf-xen_prstatus
FAIL: multixlat-elf
FAIL: multixlat-same
FAIL: xlat-linux-aarch64-5.2-va39
FAIL: xlat-linux-aarch64-5.8-va39
FAIL: xlat-linux-aarch64-5.8-va48
FAIL: xlat-linux-ppc64-64k
FAIL: xlat-linux-s390x-2l
FAIL: xlat-linux-s390x-3l
FAIL: xlat-linux-s390x-4l
FAIL: xlat-linux-x86_64-2.6.27-cr3-xen
FAIL: xlat-linux-x86_64-2.6.31-cr3
FAIL: xlat-linux-x86_64-2.6.31-nover-xen
FAIL: vmci-cleanup

[build-i686.log](https://github.com/ptesarik/libkdumpfile/files/8674125/build-i686.log)
[build-aarch64.log](https://github.com/ptesarik/libkdumpfile/files/8674127/build-aarch64.log)
[build-ppc64le.log](https://github.com/ptesarik/libkdumpfile/files/8674129/build-ppc64le.log)
[build-s390x.log](https://github.com/ptesarik/libkdumpfile/files/8674130/build-s390x.log)

**Comment by michel-slm** [comment]
Unfortunately my first attempt to enable tests, I ran them without `VERBOSE=1` so there's no data at all. This scratch build reran them verbosely:

https://koji.fedoraproject.org/koji/taskinfo?taskID=86926222

Build logs below
[build-i686.log](https://github.com/ptesarik/libkdumpfile/files/8674449/build-i686.log)
[build-aarch64.log](https://github.com/ptesarik/libkdumpfile/files/8674450/build-aarch64.log)
[build-ppc64le.log](https://github.com/ptesarik/libkdumpfile/files/8674451/build-ppc64le.log)
[build-s390x.log](https://github.com/ptesarik/libkdumpfile/files/8674454/build-s390x.log)

**Comment by michel-slm** [comment]
The same 7 tests fail on ARM 64-bit on Debian sid (unstable): https://salsa.debian.org/michel/libkdumpfile/-/blob/main/debian/patches/disable-failed-non-x86-tests.diff

**Comment by ptesarik** [comment]
Interesting. This looks like `mkelf` fails because it cannot parse the data file. There should be nothing arch-specific in that code. But I _can_ reproduce the failure on my systems, so something is indeed broken.

**Comment by ptesarik** [comment]
All right, found it. That's because `char` is unsigned on these platforms, but the code only works if `char` is signed. I'm afraid the use of `char` should be audited in all places.

**Comment by ptesarik** [comment]
With fixes up to commit 6fd240cbf8544531f1c318ffecfba2f7e5ee62df, all test now pass on my arm64, ppc64le and s390x systems. I have also tried to build an i686 version on my x86_64, but openSUSE does not provide 32-bit devel libraries, so I'd probably have to set up a new test system. If you can re-test with latest git snapshot, that would be easier for me.

**Comment by ptesarik** [comment]
Finally, I was able to get an i686 build. It still fails, so I'm keeping this issue open.

**Comment by ptesarik** [comment]
FTR my ppc64le system passes.

**Comment by ptesarik** [comment]
The tests now all pass nicely. One test is skipped on 32-bit platforms without `-D_FILE_OFFSET_BITS=64`.
