### ISSUE TITLE
diskdump-multiread and lkcd-multiread failing on Debian sid and Ubuntu jammy

### ISSUE THREAD

**Issue by michel-slm** [ptesarik/libkdumpfile#48]
Not sure what's causing this - I'll try to repro on Fedora but the last build there (from a slightly older Git tip) passed all tests

I'll attach the dump files and the build log. This is with the fa8f755 commit from earlier today (plus one patch to fix test linking, I'll submit a PR for that).

```
cat tests/test-suite.log 
==============================================
   libkdumpfile 0.4.1: tests/test-suite.log
==============================================

# TOTAL: 171
# PASS:  169
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: diskdump-multiread
========================

Creating page bitmap
Creating page data
Created DISKDUMP file: out/diskdump-multiread.dump
Bus error (core dumped)
Multi-threaded read failed
Terminated by SIGBUS
FAIL diskdump-multiread (exit status: 1)

FAIL: lkcd-multiread
====================

Creating page data
Created LKCD file: out/lkcd-multiread.dump
Read failed at 0x59000
Read failed at 0x4f000
Read failed at 0x6d000
Read failed at 0x38000
Read failed at 0x6b000
Read failed at 0x71000
Read failed at 0x7c000
Thread 0 failed: Duplicate PFN 0x0 at 262160 (previous 262144)
Thread 1 failed: Duplicate PFN 0x0 at 262160 (previous 262144)
Thread 2 failed: Duplicate PFN 0x0 at 262160 (previous 262144)
Read failed at 0x45000
Thread 3 failed: Duplicate PFN 0x0 at 262160 (previous 262144)
Thread 4 failed: Duplicate PFN 0x0 at 262160 (previous 262144)
Thread 5 failed: Duplicate PFN 0x0 at 262160 (previous 262144)
Thread 6 failed: Duplicate PFN 0x0 at 262160 (previous 262144)
Thread 7 failed: Duplicate PFN 0x0 at 262160 (previous 262144)
Multi-threaded read failed
FAIL lkcd-multiread (exit status: 1)
```
[diskdump-multiread.dump.gz](https://github.com/ptesarik/libkdumpfile/files/9311988/diskdump-multiread.dump.gz)
[lkcd-multiread.dump.gz](https://github.com/ptesarik/libkdumpfile/files/9311994/lkcd-multiread.dump.gz)
[libkdumpfile_0.4.1+20220811gitfa8f755-1_amd64.build.gz](https://github.com/ptesarik/libkdumpfile/files/9312000/libkdumpfile_0.4.1%2B20220811gitfa8f755-1_amd64.build.gz)

**Comment by ptesarik** [comment]
This smells like a locking issue. There is some support for multi-threaded programs, but it has never been tested too much, so there are likely bugs. Since most people around me use this library with Python (which is single-threaded), the bugs have probably gone unnoticed.

Anyway, I am determined to find and fix those bugs. In fact, I'm glad there will be finally some use for my early effort to make a thread-safe library.

**Comment by ptesarik** [comment]
I can reproduce the SIGBUS locally on a Debian 11 VM.

**Comment by ptesarik** [comment]
Hmmmm, it's an attempt to read from an mmap() region past EOF, so the SIGBUS is in fact correct behaviour. What is not OK is the size of `tests/out/diskdump-multiread.dump`. This is only 16384 bytes on the Debian system as opposed to the correct length of 24020 bytes.

**Comment by ptesarik** [comment]
Ugh, found it. It's that the default awk on Debian is `mawk`, which cannot parse hexadecimal numbers, so the data file that was produced with `awk` is invalid. That in turn creates an invalid dump file, and the test fails.

**Comment by ptesarik** [comment]
All tests pass on my Debian 11 system now.

**Comment by michel-slm** [comment]
ah thanks! I noticed the mawk vs gawk when comparing the drgn build outputs, but didn't think that was going to cause an issue
