### ISSUE TITLE
Copyright attribution for src/libkdumpfile/ppc64.c seems wrong?

### ISSUE THREAD

**Issue by michel-slm** [ptesarik/libkdumpfile#52]
It was initially written by @alesax - https://github.com/ptesarik/libkdumpfile/commit/268732921cbfb94c20cb2e993e1dd109c0671ce8 but his name was not on the copyright, then attributed to the FSF in https://github.com/ptesarik/libkdumpfile/commit/bae04781f419c6cb23aaf6a2bccdd9504f89966b as part of a header revamp.

Looking at the git log, looks like all changes made to this file are done by @alesax and @ptesarik

**Comment by ptesarik** [comment]
You're right, ppc64 was contributed by Aleš. Let me change the attribution.
