### ISSUE TITLE
Parallel test failure (xlat-linux-x86_64-6.11-pti-user, xlat-linux-x86_64-6.11-pti-user-ver)

### ISSUE THREAD

**Issue by thesamesam** [ptesarik/libkdumpfile#85]
These two tests seem to fail for me sporadically with parallel `make check` with master/0.5.5).

After running `make check -j32 -l32` 3 times, I hit:
```
FAIL: xlat-linux-x86_64-6.11-pti-user
=====================================

Checking... Malformed param: -pti-user.data
FAILED
FAIL xlat-linux-x86_64-6.11-pti-user (exit status: 1)

FAIL: xlat-linux-x86_64-6.11-pti-user-ver
=========================================

Checking... Malformed param: -pti-user.data
FAILED
FAIL xlat-linux-x86_64-6.11-pti-user-ver (exit status: 1)
```

**Comment by ptesarik** [comment]
Hi Sam,
thank you for your report. It looks like the test prefix (`xlat-linux-x86_64-6.11`) is empty under some conditions. I'll try to reproduce it here and ask you for more details if that fails.

**Comment by ptesarik** [comment]
Found it: `xlat-linux-x86_64-6.11-pti-user` and `xlat-linux-x86_64-6.11-pti-user-ver` use the same input files, but the logic is flawed, because they also use the same output file names. Let me fix it.

**Comment by thesamesam** [comment]
Thanks @ptesarik! I would've just sent a patch but I couldn't spot it immediately yesterday.
